### ISSUE TITLE
Incompatible glyphs "hha_khm" in NotoSansMyanmarUI-MM.glyphs and NotoSansMyanmar-MM.glyphs

### ISSUE THREAD

**Issue by xiangyexiao** [googlei18n/noto-fonts#798] opened 2016-11-30 22:03 UTC
fontmake -g src/NotoSansMyanmar/NotoSansMyanmar-MM.glyphs --mti-source src/NotoSansMyanmar/NotoSansMyanmar-MM.plist -o variable

>> Building interpolation-compatible TTFs
Traceback (most recent call last):
  File "/usr/local/bin/fontmake", line 9, in <module>
    load_entry_point('fontmake', 'console_scripts', 'fontmake')()
  File "build/bdist.macosx-10.11-x86_64/egg/fontmake/__main__.py", line 109, in main
  File "build/bdist.macosx-10.11-x86_64/egg/fontmake/font_project.py", line 317, in run_from_glyphs
  File "build/bdist.macosx-10.11-x86_64/egg/fontmake/font_project.py", line 358, in run_from_designspace
  File "build/bdist.macosx-10.11-x86_64/egg/fontmake/font_project.py", line 423, in run_from_ufos
  File "build/bdist.macosx-10.11-x86_64/egg/fontmake/font_project.py", line 178, in build_interpolatable_ttfs
  File "/Users/xiangye/Library/Python/2.7/lib/python/site-packages/fontTools/misc/loggingTools.py", line 372, in wrapper
    return func(*args, **kwds)
  File "build/bdist.macosx-10.11-x86_64/egg/fontmake/font_project.py", line 138, in convert_curves
  File "/Users/xiangye/Library/Python/2.7/lib/python/site-packages/cu2qu/ufo.py", line 195, in fonts_to_quadratic
    _fonts_to_quadratic(fonts, max_errors, reverse_direction, stats)
  File "/Users/xiangye/Library/Python/2.7/lib/python/site-packages/cu2qu/ufo.py", line 155, in _fonts_to_quadratic
    'Incompatible glyphs "%s"' % name)
AssertionError: Incompatible glyphs "hha_khm"

fontmake -g src/NotoSansMyanmarUI/NotoSansMyanmarUI-MM.glyphs --mti-source src/NotoSansMyanmarUI/NotoSansMyanmarUI-MM.plist -o variable
>> Building interpolation-compatible TTFs
Traceback (most recent call last):
  File "/usr/local/bin/fontmake", line 9, in <module>
    load_entry_point('fontmake', 'console_scripts', 'fontmake')()
  File "build/bdist.macosx-10.11-x86_64/egg/fontmake/__main__.py", line 109, in main
  File "build/bdist.macosx-10.11-x86_64/egg/fontmake/font_project.py", line 317, in run_from_glyphs
  File "build/bdist.macosx-10.11-x86_64/egg/fontmake/font_project.py", line 358, in run_from_designspace
  File "build/bdist.macosx-10.11-x86_64/egg/fontmake/font_project.py", line 423, in run_from_ufos
  File "build/bdist.macosx-10.11-x86_64/egg/fontmake/font_project.py", line 178, in build_interpolatable_ttfs
  File "/Users/xiangye/Library/Python/2.7/lib/python/site-packages/fontTools/misc/loggingTools.py", line 372, in wrapper
    return func(*args, **kwds)
  File "build/bdist.macosx-10.11-x86_64/egg/fontmake/font_project.py", line 138, in convert_curves
  File "/Users/xiangye/Library/Python/2.7/lib/python/site-packages/cu2qu/ufo.py", line 195, in fonts_to_quadratic
    _fonts_to_quadratic(fonts, max_errors, reverse_direction, stats)
  File "/Users/xiangye/Library/Python/2.7/lib/python/site-packages/cu2qu/ufo.py", line 155, in _fonts_to_quadratic
    'Incompatible glyphs "%s"' % name)
AssertionError: Incompatible glyphs "hha_khm"

**Comment by marekjez86** [comment] 2016-12-05 17:58
duplicate of https://github.com/googlei18n/noto-fonts/issues/801 (MTI still working on interpolatibility of Myanmar)

**Closed by marekjez86** 2016-12-05 17:58 UTC
Labels: Script-Myanmar
