### ISSUE TITLE
Italiscied numbers in Regular parentheses

### ISSUE THREAD

**Issue by elTooDR** [googlei18n/noto-fonts#789] opened 2016-11-08 15:53 UTC
Character spacing between regular parentheses and italicized numbers is either too large (aesthetically) or are touching.

Noto Sans
Example (_123123123_)

![123](https://cloud.githubusercontent.com/assets/23340932/20105952/deeda2e8-a5d3-11e6-9768-975bec51b058.PNG)

**Comment by dougfelt** [comment] 2016-11-08 18:10
This seems like it should be up to your rendering pipeline.  These characters cross font boundaries, and if for example parentheses were designed to fit with whatever text might be placed next to them, the spacing of the parentheses with regular text would be too large.  Higher levels of the rendering system could identify such situations and adapt to them, but I don't think it's the font's job.

**Comment by marekjez86** [comment] 2016-11-10 00:14
@dougfelt : agreed "it should be up to your rendering pipeline".  I should close the issue for the noto-fonts, but I don't know where to place it yet. Hence I keep it open.

**Comment by hrhatada** [comment] 2016-11-14 21:45
Hi elTooDR, I checked the example you showed with TextEdit & Chrome on OSX, but I could not reproduce it.  Please refer to the attached screenshots for the test result.

As dougfelt & marekjez86 pointed out, the issue you reported is not the font issue, but the fonts rendering engine issue.

![image](https://cloud.githubusercontent.com/assets/16353449/20283941/f8ac213c-aa6f-11e6-8705-395ec9bdeb12.png)

![image](https://cloud.githubusercontent.com/assets/16353449/20283960/06363bd0-aa70-11e6-92f9-0539387bb940.png)

**Closed** 2016-11-28 23:26 UTC

**Comment by elTooDR** [comment] 2016-12-13 11:17
Apologies for not writing back earlier.

You are correct, I had installed OTF fonts on Win 10 and this as the issue. TTF are fine.
