### ISSUE TITLE
LGC: Space on the right side of U+02DE MODIFIER LETTER RHOTIC HOOK is too tight

### ISSUE THREAD

**Issue by jungshik** [googlei18n/noto-fonts#435] opened 2015-07-29 18:59 UTC
Moved from googlei18n/noto-alpha#258
Imported from [Google Code issue #258](https://code.google.com/a/google.com/p/noto-alpha/issues/detail?id=258) created by [roozbeh@google.com](https://code.google.com/u/roozbeh@google.com/) on 2014-10-26T02:22:07.000Z:

---

See the attached renderings of the sequence &quot;fɑ˞m&quot; in Noto Sans, Noto Serif, and Cambria. The problem exists with other combinations of the character too.

![noto-sans](https://cloud.githubusercontent.com/assets/12721521/8658103/a5cd694e-2956-11e5-8b4e-e98213d9cb50.png)
![noto-serif](https://cloud.githubusercontent.com/assets/12721521/8658104/a5d1bae4-2956-11e5-8865-a6658a7399dc.png)
![cambria](https://cloud.githubusercontent.com/assets/12721521/8658102/a5c7ec4e-2956-11e5-90b1-81adefaa67b0.png)

**Comment by fontguy** [comment] 2015-07-29 23:49
Probably requires kerning adjustment.

**Comment by marekjez86** [comment] 2016-12-29 06:46
All fixed in Noto (see below for results) - hence this bug should be closed for Noto fonts.
To verify I used the following test:

```html
<html lang="en">
	<p><span style="font-weight:700">fɑ˞mɚmɝm</span></p>
</html>
```

Note Roboto fails the test (hence assigning to @roozbehp [it's marked with Platform-Android label and Medium-Priority]:

![en-435](https://cloud.githubusercontent.com/assets/13322623/21538204/47c01aba-cd4f-11e6-9ed0-25dc52ac030c.jpeg)

the results for Noto and Roboto are as follows 

[en-435-NotoSans-Black.pdf](https://github.com/googlei18n/noto-fonts/files/676691/en-435-NotoSans-Black.pdf)
[en-435-NotoSans-Italic.pdf](https://github.com/googlei18n/noto-fonts/files/676695/en-435-NotoSans-Italic.pdf)
[en-435-NotoSans-Regular.pdf](https://github.com/googlei18n/noto-fonts/files/676693/en-435-NotoSans-Regular.pdf)
[en-435-NotoSansDisplay-Black.pdf](https://github.com/googlei18n/noto-fonts/files/676694/en-435-NotoSansDisplay-Black.pdf)
[en-435-NotoSansDisplay-Italic.pdf](https://github.com/googlei18n/noto-fonts/files/676692/en-435-NotoSansDisplay-Italic.pdf)
[en-435-NotoSansDisplay-Regular.pdf](https://github.com/googlei18n/noto-fonts/files/676696/en-435-NotoSansDisplay-Regular.pdf)
[en-435-NotoSansMono-Black.pdf](https://github.com/googlei18n/noto-fonts/files/676698/en-435-NotoSansMono-Black.pdf)
[en-435-NotoSansMono-Regular.pdf](https://github.com/googlei18n/noto-fonts/files/676697/en-435-NotoSansMono-Regular.pdf)
[en-435-NotoSerif-Black.pdf](https://github.com/googlei18n/noto-fonts/files/676699/en-435-NotoSerif-Black.pdf)
[en-435-NotoSerif-Italic.pdf](https://github.com/googlei18n/noto-fonts/files/676702/en-435-NotoSerif-Italic.pdf)
[en-435-NotoSerif-Regular.pdf](https://github.com/googlei18n/noto-fonts/files/676700/en-435-NotoSerif-Regular.pdf)
[en-435-NotoSerifDisplay-Black.pdf](https://github.com/googlei18n/noto-fonts/files/676701/en-435-NotoSerifDisplay-Black.pdf)
[en-435-NotoSerifDisplay-Italic.pdf](https://github.com/googlei18n/noto-fonts/files/676703/en-435-NotoSerifDisplay-Italic.pdf)
[en-435-NotoSerifDisplay-Regular.pdf](https://github.com/googlei18n/noto-fonts/files/676707/en-435-NotoSerifDisplay-Regular.pdf)
[en-435-Roboto-Black.pdf](https://github.com/googlei18n/noto-fonts/files/676705/en-435-Roboto-Black.pdf)
[en-435-Roboto-Italic.pdf](https://github.com/googlei18n/noto-fonts/files/676706/en-435-Roboto-Italic.pdf)
[en-435-Roboto-Regular.pdf](https://github.com/googlei18n/noto-fonts/files/676704/en-435-Roboto-Regular.pdf)

**Comment by roozbehp** [comment] 2016-12-29 06:54
@jamesgk, please file a bug in Robot's repo and flag it accordingly.

**Comment by jamesgk** [comment] 2017-01-03 21:07
This bug does not exist in the latest Roboto.

**Comment by marekjez86** [comment] 2017-01-03 22:04
@jamesgk : what do you get when you print
```html
	<p><span style="font-weight:700">fɑ˞mɚmɝm</span></p>
```
with the latest roboto?

I get
![en-phonipa-435](https://cloud.githubusercontent.com/assets/13322623/21624819/629cc53c-d1bd-11e6-936f-364dbf4e34b6.jpeg)
which could mean that some of the IPA characters were removed from the font. Could you check?

**Comment by jamesgk** [comment] 2017-01-03 22:10
For me it renders the characters:

![roboto](https://cloud.githubusercontent.com/assets/988758/21624986/5e8b6fce-d1be-11e6-9c0f-d1f8db5b852f.png)

Which "latest roboto" are you using exactly (from github / google fonts / android)?

**Comment by marekjez86** [comment] 2017-01-03 22:22
@jamesgk : fixed in Roboto. Unable to reproduce it with the latest one. thanks.

**Closed by marekjez86** 2017-01-03 22:22 UTC
Labels: Android, FoundIn-1.x, Priority-Medium, Script-LatinGreekCyrillic, Status-NotoFixed, Type-Defect
