### ISSUE TITLE
Unsharp rendering at font size 8 to 10

### ISSUE THREAD

**Issue by sebastic** [googlei18n/noto-fonts#556] opened 2015-11-10 17:46 UTC
With the removal of the Droid font in Debian, the JOSM package will switch to the Noto font.

The JOSM developers remarked in [JOSM issue #12085](https://josm.openstreetmap.de/ticket/12085) that the rendering at small font sizes is not sharp as demonstrated in this GIF:
![noto](https://cloud.githubusercontent.com/assets/4605306/11070273/14332d5a-87db-11e5-8d22-a9901fcc4602.gif)

Is it possible to improve the sharpness at small font sizes? That would remove the barrier to switch to Noto.

**Comment by dougfelt** [comment] 2015-11-10 17:55
@Behdad, any suggestions?

**Comment by behdad** [comment] 2015-11-12 09:04
Is it the hinted noto?  This is a problem best answered on the freetype-devel mailing list, and only after inspecting the actual fonts used and the FreeType settings involved.

**Comment by sebastic** [comment] 2015-11-12 20:47
Yes, it's hinted noto.

![josm-droid-noto](https://cloud.githubusercontent.com/assets/4605306/11130218/20e0c6b6-8984-11e5-8f43-b8b6351c2e05.png)
The above example is of JOSM 8969 using the embedded copy of the Droid font from their SVN repo ([DroidSans.ttf](https://josm.openstreetmap.de/browser/josm/trunk/data/fonts/DroidSans.ttf)) on left, and the Noto font from the fonts-noto (2015-05-11+cjk-1) Debian package ([NotoSans-Regular.ttf](https://sources.debian.net/src/fonts-noto/2015-05-11%2Bcjk-1/fonts/individual/hinted/NotoSans-Regular.ttf/)) on the right. This is on Debian unstable with freetype (2.6-2) and OpenJDK 7 (7u91-2.6.2-1).

**Comment by bastik** [comment] 2015-11-13 02:57
You can see the difference by calling the following commands:
```
$ ftview -m 'Bizonweide ' 8 DroidSans.ttf
$ ftview -m 'Bizonweide ' 8 NotoSans-Regular.ttf
```
The font file is from the Noto-hinted.zip which is for download on the Noto website. I can provide screenshots, and system details if needed.

**Comment by behdad** [comment] 2015-11-13 05:00
Then this definitely needs to be reported to freetype-devel and followed up.

**Comment by bastik** [comment] 2015-11-13 15:05
In `ftview`, you can use the shortcut 'h' to toggle hinting. I noticed that for Noto, it makes no difference, if hinting is on or off, both renderings look the same. If you turn hinting off for Droid though, it gets blurry, similar to how it looks for Noto in either setting.

In other words, it seems as if the hinting is completely disabled for the FreeType rendering of Noto.

> Then this definitely needs to be reported to freetype-devel and followed up.

Who is this directed at?

**Comment by sebastic** [comment] 2015-11-13 18:25
On 13-11-15 16:05, bastik wrote:
> In `ftview`, you can use the shortcut 'h' to toggle hinting. I noticed that for Noto, it makes no difference, if hinting is on or off, both renderings look the same. If you turn hinting off for Droid though, it gets blurry, similar to how it looks for Noto in either setting.
> 
> In other words, it seems as if the hinting is completely disabled for the FreeType rendering of Noto.

The unhinted NotoSans-Regular.ttf is about a sharp as the DroidSans.ttf
included in JOSM.

>> Then this definitely needs to be reported to freetype-devel and followed up.
> 
> Who is this directed at?

Either of us I guess, so I started a thread on freetype-devel:

http://lists.nongnu.org/archive/html/freetype-devel/2015-11/msg00096.html

**Comment by marekjez86** [comment] 2016-01-15 20:37
Since this is handled within http://lists.nongnu.org/archive/html/freetype-devel/2015-11/msg00096.html I believe I can close it here. @sebastic please reopen if I'm wrong.

**Closed by marekjez86** 2016-01-15 20:37 UTC

**Comment by bastik** [comment] 2016-01-31 00:37
**marekjez86**: It is not clear yet, if the broken hinting is caused by a bug in freetype or if the noto font needs to be improved. There was only one reply to the post on the freetype mailing list: A freetype developer mentioned his [work](https://github.com/lemzwerg/noto-hinted) on a hinted version of noto produced with ttfautohint (a software project he is also involved in).

I cannot tell if this work will be any help, but in the end, it would be great if the _official noto releases_ were freetype-compatible in terms of hinting!
