### ISSUE TITLE
Noto Mono Feature Request. Adding a slash or bullet to the Number 0

### ISSUE THREAD

**Issue by Rixius** [googlei18n/noto-fonts#761] opened 2016-10-10 15:23 UTC
Greetings, downloaded Noto and began to play around with it. First thing I noticed was that, like Droid Sans, the Zero has not been better differentiated from an English capital O.

Example:
![character differences](https://cloud.githubusercontent.com/assets/300226/19241131/cd258a16-8ed2-11e6-9052-715d4005c123.png)

For better source code viewing, adding some artifact to better distinguish the characters would be a benefit.

**Comment by dougfelt** [comment] 2016-10-10 15:37
duplicate of #755

**Closed by dougfelt** 2016-10-10 15:37 UTC
