### ISSUE TITLE
Noto Sans Kannada: issue with nukta and consonant conjugate

### ISSUE THREAD

**Issue by MayuraVerma** [googlei18n/noto-fonts#971] opened 2017-10-01 23:49 UTC
### Title 
  > Noto Sans Kannada: issue with nukta and consonant conjugate

### Font 
  > 'NotoSansKannada-Regular.ttf'.

### Where the font came from, and when
  >   http://kannadafont.blogspot.com/2017/10/case-10-nukta-with-consonant-conjugate.html
  >   With Nukta at the end of letters, breaks the letters
        FAILS->
        ಕ್ಕ಼   (single consonant conjugate with nukta at the end)
        ಕ್ಕ್ರ಼   (double consonant conjugate)

### Font Version
  > Version 1.03 uh

### OS name and version
  > Mac OS High Sierra GM

### Application name and version
  > Google Chrome, Version 61.0.3163.100 (Official Build) (64-bit)

### Issue
  > Summarize the issue briefly -- one paragraph preferred

  1. Steps to reproduce
  2. Observed results
  3. Expected results
  4. Additional information 
  > Unicode chart, technical specs, shaping info, comparison with non-Noto fonts, comparison with earlier version of the same font (regression cases)

### Character data
  > Please include real character data to illustrate your issue-- Unicode codepoints are helpful.  This makes it possible for developers who don't know the language or script to copy/paste the text to reproduce the issue.

### Screenshot
  > If possible, include a screenshot or an image illustrating the issue.
  > Annotations are also helpful.

## Tools for reporting bugs
  Useful tools for reporting bugs are available at: https://github.com/googlei18n/
  
### Harfbuzz hb-view and hb-shape
  These are part of the HarfBuzz distribution and can help isolate if an issue is in the app/OS, shaping engine, or font.
  * hb-view renders the text with the exact font (for example, to see how ligatured characters shape) using your installed version of HarfBuzz.

For example:
```
  hb-view --font-file {path to font} --text-file {path to text file} --output-file '{sample}.png'
```

* hb-shape shows glyph selection and positioning

### Fontview
  * Fontview displays the text.

### Fontdiff
  * Fontdiff displays the text using two versions of the font side by side.

**Comment by MayuraVerma** [comment] 2017-10-02 00:52
Please review this below page for more combinations

http://kannadafont.blogspot.com/2017/09/case-6c-nukta-combination-with-google.html

**Comment by marekjez86** [comment] 2017-10-03 13:58
added https://github.com/googlei18n/noto-source/blob/master/test/Kannada/kn-971.html as a test

**Comment by JelleBosmaMT** [comment] 2017-10-03 14:31
The nukta should be entered right behind the consonant.

![untitled 2](https://user-images.githubusercontent.com/12729011/31130528-f2253182-a857-11e7-84bb-7234b3a33163.png)

See this image showing that it works that may.

With the given examples the Safari browser gives dotted circles, indicating invalid unicode sequences. I don't quite understand why the Chrome browser doesn't.

**Comment by MayuraVerma** [comment] 2017-10-03 15:13
@JelleBosmaMT Could you please confirm this in the Unicode document. I can't see reference for Kannada, my bad!
But if this is true, then it can be controlled/constrained in the native Kannada keyboard. 
Please advise.

**Comment by JelleBosmaMT** [comment] 2017-10-03 15:22
Not sure what Unicode document you are talking about?

**Comment by MayuraVerma** [comment] 2017-10-03 15:30
http://www.unicode.org/versions/Unicode10.0.0/ch12.pdf

**Comment by JelleBosmaMT** [comment] 2017-10-04 08:12
I am afraid, I am just a type designer, not one of the authors of the Unicode specification. Chapter 12 gives a lot of information in the section about Devanagari. It would have been better to have a separate section on common principles of the Indic scripts, rather than relying on people reading about Devanagari and then translate the render rules to the other scripts where applicable. 

In Kannada we have ಜ and ಫ known to combine with the nukta, and sometimes ಸ. Noto Sans Kannada tries to support all consonants. But I haven't seen conjuncts with 2 or more consonants where the nukta is used for a consonant which isn't the first. So consonants with nukta's are not rendered with their subscript form, but always in full.

**Comment by MayuraVerma** [comment] 2017-10-04 16:17
@JelleBosmaMT Thank you. I am not an expert in unicode standard. 
I am helping the Kannada community with Unicode fonts and keyboard drivers. Legal unicode sequence for Kannada Nukta is not clearly written in Unicode specs. When I asked this question with Kannada linguistics, they felt its better to leave it outside the consonant conjugate and diacritics. This way when user search for "ಕ್ನ್ಕೇ" they get both "ಕ್ನ್ಕೇ" and "ಕ್ನ್ಕೇ಼". But if the Nukta sits inside "ಕ಼್ನ್ಕೇ" the cluster, then we can't find the text. Nirmala font (windows 7/10 UI) supports both with few exceptions.

I clearly don't know which one is correct form. Is there way to get clarity on this from unicode consortium. If we have to follow the Devanagiri method, thats fine. But somewhere this needs to be documented.

It could outside the font issue, but related! Please advise.

**Comment by roozbehp** [comment] 2017-10-04 17:56
The easiest way for asking Unicode to document something is contacting them using the contact form, here: https://www.unicode.org/reporting.html

**Comment by MayuraVerma** [comment] 2017-10-05 04:06
@roozbehp @JelleBosmaMT 
Thank you.

**Comment by sridatta1** [comment] 2017-10-06 16:55
I was about to file issue on nukta on subscripts
I Kannada nukta is generally used on for f ಫ಼ z ಜ಼ in English and Perso-arabic words.
In words like pizza ಪಿಜ಼್ಜ಼ಾ gulf  ಗಲ್ಫ಼್ waqf ವಕ್ಫ಼್  In these words consonant with nukta is a non-initial consonant of the cluster. Subscript forms with nukta should also be supported for f z, though these aren't commonly seen in other fonts thus these words are also written without nukta.

**Comment by MayuraVerma** [comment] 2017-10-06 18:01
@sridatta1 
If in pizza, we need nukta both base and conjugate "ಜ" in ಪಿಜ್ಜಾ.
It could be very complicated. We need to approach Unicode consortium to get this written in the manual.

**Comment by MayuraVerma** [comment] 2017-10-06 18:13
@sridatta1 if you see possibility of having nukta in the ottakshara, then we need to specify in the Unicode standard that the nukta needs to sit right next to the consonant. It is not clear in the standard.

**Comment by sridatta1** [comment] 2017-10-07 09:39
The common principles of Indic scripts are specified in Devanagari Chapter
See R9 pg 457 of chapter 12.1 of core specification 
Subscript/ottu forms with nukta should be rendered as below mainly for ಫ಼ ಜ಼ (Murty Kannada font)
![nukta](https://user-images.githubusercontent.com/23263723/31306615-4dceb96a-ab71-11e7-8e04-de5fec23a1a1.JPG)

**Comment by MayuraVerma** [comment] 2017-10-09 20:50
@sridatta1 Thank you. Most of the Kannada fonts would fail with these combinations. 

Can you please add if more words to justify the change with other fonts.

Also, do you know how to approach the Microsoft to get this rectified in Tunga and Nirmala.

**Comment by JelleBosmaMT** [comment] 2017-10-11 08:15
I had to think about this.

There are two reasons why Noto Sans Kannada doesn't have subscript forms with nukta.
- In a prototype version I added subscript forms of Za and Fa, but discovered that shaper software refused to display them. Not much point keeping them.
- When used in small sizes as screen font the subscripts are quite small and hard enough to read. Two dots below the subscripts are not recognizable as dots, they just blur the subscript.

So now in 2017 when I try adding subscript Za and Fa and try them, the document version of the regular font looks like this in the Chrome, Safari (El Capitan) and Edge Browsers:

![document nukta](https://user-images.githubusercontent.com/12729011/31427778-c97ea8e6-ae68-11e7-8aa7-800654f4b233.png)

Only Chrome treats conjuncts with nukta the same as those without. The Microsoft shaper doesn't re-order the vowel sign before the subscript as it would normally do. It will require a work-around in the font.

On the Mac the fonts are displayed heavier than they really are. But even then I think I should move the nukta a bit further away from the subscript Ja and Pha, in order to improve legibility at small sizes.

But that will be difficult in the UI version of the fonts, where there is no room to put anything below the existing subscripts. So these have to be moved up to make room and then it looks like this:
![ui nukta](https://user-images.githubusercontent.com/12729011/31428208-5b68fb66-ae6a-11e7-9899-1ab49e22526d.png)

The plan is to add some additional characters to Noto Sans Kannada, such as the new candrabindu's, and to add additional weights and widths: from thin to black and from normal width to extra condensed. Actually I send Google a design proposal last week. I will modify this proposal to add support for subscript Fa and Za and wait to hear if they and their expert reviewers agree. I am not sure if it makes sense to add support for any combination of subscript with nukta. For the UI version that seems hopeless, as it would require 3 separate glyphs for each combination. A lot of work for combinations that may never be used, may not be legible when they are used, and I have less time to spend on characters that are used.
For the normal document version, it might be possible to add a nukta that is displayed below the other subscript consonants. But I am not sure if it a good idea. It may be correct in following the render rules of Kannada, but I am not sure if it is user friendly. I can imagine it will be more often than not a misspelling that needs to be corrected, and then using the full form the user can see there is a nukta, rather than a subscript with a blur?

**Comment by JelleBosmaMT** [comment] 2017-10-11 08:27
Huh, I just see that in the samples above the syllable "Z-Jaa" is different in Chrome, because the Ja subscript isn't moved below the vowel sign, as it does in Edge and Safara. So Google _and_ Apple _and_ Microsoft have a bug rendering nukta, it is just three different bugs!! 😢

**Comment by kalapi** [comment] 2017-10-16 05:42
I can confirm that this has been incorporated in the latest build of Noto Serif Kannada without the need of below-base nuke variant glyphs. Additionally, as seen in the last four clusters, the below base consonants shift rightward when the base consonant has a _nukta_ so that they don't collide.

<img width="679" alt="screen shot 2017-10-12 at 6 48 55 pm" src="https://user-images.githubusercontent.com/15804460/31594947-eb317158-b255-11e7-943d-960353619905.png">
<img width="689" alt="screen shot 2017-10-12 at 6 48 43 pm" src="https://user-images.githubusercontent.com/15804460/31594948-eb6d6fc8-b255-11e7-9503-ecacb450b19c.png">
<img width="743" alt="screen shot 2017-10-12 at 6 48 05 pm" src="https://user-images.githubusercontent.com/15804460/31594949-eba5556e-b255-11e7-9c18-c87f4ce91440.png">
<img width="738" alt="screen shot 2017-10-12 at 6 48 29 pm" src="https://user-images.githubusercontent.com/15804460/31594950-ebdce8c6-b255-11e7-846d-2019e095233b.png">

Tested on the following platforms:
#### OSX 10.11.6:
- [working as expected] Google Chrome Version 61.0.3163.100 (Official Build) (64-bit)
- [working as expected] Mozilla Firefox Version 56.0 (64-bit)
- [_not_ working as expected] Safari Version 10.1.2 (11603.3.8)

#### Windows 8.1:
- [working as expected] Google Chrome Version 61.0.3163.100 (Official Build) (64-bit)
- [working as expected] Mozilla Firefox Version 56.0.1 (64-bit)
- [working as expected] Internet Explorer 11.0.9600.18763

* Haven't tested on Edge yet as my VM is having some issues. Will update this as soon as I can test it. Same for Ubuntu although I presume that Chrome and FireFox will work as expected.

**Comment by MayuraVerma** [comment] 2017-10-16 06:24
is it possible to get a copy of the new build for testing?
Also, please check the same with libreoffice. Although libreoffice uses harfbuzz, there seems to be some issue with complex text.

**Comment by kalapi** [comment] 2017-10-16 09:06
@MayuraVerma 

Unfortunately i'm unable to provide a binary at this time, but it should be available soon. I'm also reviewing all Kannada specific issues in this repo and testing against the latest files.

With regards to LibreOffice:

This is Version: 5.3.6.1 on OSX 10.11.6 with Kannada selected under `Preferences>Language Settings>Languages>Complex text layout (CTL)`

![screen shot 2017-10-16 at 2 32 23 pm](https://user-images.githubusercontent.com/15804460/31603928-59267db0-b27f-11e7-898a-e35abf70ba71.png)

**Comment by JelleBosmaMT** [comment] 2017-10-16 12:15
@kalapi (off topic)
I assume the sample showing thin to black are not at the same point size, with the thin at the largest. But even then the virama of the Thin weight looks too large. Mostly the top half being very large and more in a constructed style as the intent of the design (It was me who made the original design proposal in 2014, so I am pardoned to have an opinion).

**Comment by kalapi** [comment] 2017-11-09 17:37
@JelleBosmaMT 
Sorry for the late reply. I've now fixed this in the latest version. Thank you for pointing out this issue. While testing the design my sample texts did not contain words which ended with a viral which is why I missed this. I have now included this in my standard test.

Example 1:
![screen shot 2017-11-09 at 11 03 29 pm](https://user-images.githubusercontent.com/15804460/32620062-a218ffc6-c5a2-11e7-90da-83c19efecec2.png)

Example 2:
![screen shot 2017-11-09 at 10 58 55 pm](https://user-images.githubusercontent.com/15804460/32620110-c81e1666-c5a2-11e7-8d2f-5b2cce918f4a.png)

**Comment by MayuraVerma** [comment] 2017-11-20 01:32
In mac OS beta "10.13.2 Beta (17C79a)”, nukta is supported for subscript. 

I have tested the Noto Sans Kannada. It is rendering as expected.

Noto Sans Kannada in Pages on mac OS public beta 4.
![screen shot 2017-11-19 at 7 30 01 pm](https://user-images.githubusercontent.com/14062593/32998364-198b6d04-cd60-11e7-86ff-cd30b44433c7.png)

I request please consider supporting nukta for all consonants in subscript form as its done in "Murty" font.

**Comment by puneethk4** [comment] 2018-03-17 18:47
Not sure if this is the right place to ask this query. Wanted to know how to write pizza, gulf, waqf in kannada as in above post.

(Please let me know the exact keystrokes, I am using Inscript Keyboard Layout)

I am already having Noto Sans Kannada in Pages on latest mac OS. Also Libre Office 5.4.5 with CTL selected.

Max I could write was only

![nukta_issue](https://user-images.githubusercontent.com/2357243/37558907-b96209bc-2a41-11e8-8e96-9b3916e30f1c.jpg)

**Comment by MayuraVerma** [comment] 2018-03-19 20:24
@puneethk4 
Noto Sans Kannada updated test version is posted here https://github.com/googlei18n/noto-fonts/issues/973#issuecomment-336591932
Only this version supports the nukta in vattu.
Or you can use Murty-Kannada font.

In Pages, Numbers and Keynotes: Please check the mac OS version, it should be above 10.13.2 for apple applications to render this text correctly. Apple applications uses Apple Core-Text shaping engine.
Check the font and mac OS version.

In LibreOffice, you need version above 5.4.2, which you already have. Libreoffice should render correctly independent of mac OS version though, because it uses harfbuzz shaping engine.
Check the font you are using.

FYI: Font and shaping engine both must support the feature to render OpenType font.

**Comment by puneethk4** [comment] 2018-03-20 14:24
@MayuraVerma  Thank You. It worked in Pages/Murthy Font. Murthy Font download website was down over the weekend, hence couldn't use it earlier and was only checking with officially available Noto Sans which wasn't working.

Any Idea on when above mentioned Noto Sans Kannada will be officially available?

~Thanks, Puneeth

**Comment by sridatta1** [comment] 2018-03-20 16:33
Also check the latest alpha fonts of Noto Serif Kannada, they might support
nukta with subscripts
https://github.com/googlei18n/noto-fonts-alpha/tree/master/from-pipeline/unhinted/otf/serif/NotoSerifKannada

sequence- Ja+ nukta+ Virama+Ja+nukta + vowel sign AA and similarly others

**Closed** 2018-12-10 15:20 UTC
Labels: Script-Kannada
