### ISSUE TITLE
Dot position in Noto Urdu Nastaliq: draft version works better

### ISSUE THREAD

**Issue by RolfNoyer** [googlei18n/noto-fonts#714] opened 2016-06-21 00:47 UTC
Using Mac OSX 10.10.5 Yosemite with applications Text Edit, File Maker Pro Advanced 13, and Libre Office, the dots on certain connecting letters are placed too low relative to the base position in Noto Nastaliq Urdu, but *not* in Noto Nastaliq Urdu “Draft”, which does not have the bug. 

Examples:  U+062A ARABIC LETTER TEH
                   U+062B ARABIC LETTER THEH
                   U+0634 ARABIC LETTER SHEEN
                   U+0679 ARABIC LETTER TTEH

all have dots or other diacritics above. These appear too low, and are even superimposed on the base glyph, when the letter in question appears as a connecting form and preceding certain other letters, for example:

                  U+0468  ARABIC LETTER WAW
                  U+0628  ARABIC LETTER BEH
                  U+0631 ARABIC LETER REH
                  U+06D2 ARABIC LETTER HAH
                  U+064A ARABIC LETTER YEH
                  U+0644  ARABIC LETTER LAM

Letters with diacritics below the glyph, such as U+062C ARABIC LETTER JEEM show the dot(s), etc., vertically displaced lower than in the “Draft” version by the same amount that the diacritics above are displaced downward. For letters with diacritics below this is less problematic because the dots are not actually covering the base glyph, but this still shows that there is a general problem with positioning diacritics.

In the attached .png, please see examples written in the “Draft” version (marked “draft -- good”) and in the (later released) version, marked “bad”:

![nastaliq dot placement problems](https://cloud.githubusercontent.com/assets/19880049/16214580/e886cd68-3727-11e6-9866-97d067b10726.png)

 
Note that  U+0646 ARABIC LETTER NOON appears to be unaffected by the problem. Some examples of NOON also appear in the .png attached. 

I have also noticed the problem does not occur in Mellel (word processor for Mac), which displays both fonts correctly.

**Comment by behdad** [comment] 2016-06-30 20:49
Where did you get each version of the font?

**Comment by RolfNoyer** [comment] 2016-06-30 23:28
I am not sure where I got the two versions, but probably I got them through the “Early Access” page with all the fonts that are in development and have not yet “graduated”:

https://www.google.com/fonts/earlyaccess

I don’t think the Nastaliq font is in the huge github package which contains all the Noto fonts, but if it is, I might have gotten it out of that package.

What might be more informative are the version numbers (?):

Noto Nastaliq Urdu Version 1.02 uh  (the one with the bugs: last stated modification date: 11 Feb 2016)

Noto Nastaliq Urdu Version 0.70  (the one that works better: last stated modification date: 9 June 2015)

Before filing the bug report I checked to see if I could find any newer versions in the usual places but did not see any.

I have noticed some other issues in diacritic mark placement where the “Draft” version of Noto Nastaliq works better than the non-“Draft” version (positioning of kasra, sukūn, and so forth). If you think this is worth pursuing and you want details I can work up some specific cases for you.

BTW, maybe relevant:

I’ve noticed all sorts of issues about the display of Arabic fonts (not just Nastaliq ones) using various Mac applications. The most incomprehensible thing is that certain bugs show up in one application but not another in a seemingly random way. I am assuming that this all depends on how the apps deal with complex text layout instructions like cursive attachment and diacritic “mark” placement, but I don’t know a lot about that.

For example, Mellel (a word processor for Mac) does fine with both versions of Noto Nastaliq Urdu that I have, but Mac’s File Maker, Libre Office and Text Edit _do_ have the dot-placement problem.

On the other hand Mellel has a bug with Hussaini Nastaleeq (the realization of “medial yeh’ is messed up, and nothing at all can be done about it).  But that bug does not show up in File Maker, Libre Office or Text Edit.  

All the Naskh fonts produced by Pak Type have some bugs which show up in File Maker, Libre Office and Text Edit, but not Mellel. (See discussion at https://sourceforge.net/p/paktype/bugs/3/). This is the same bug “distribution” as for Noto Nastaliq non-Draft. According to the designer of those fonts, these bugs cannot be reproduced in Windows.

Open Office for Mac displays Noto Naskh Arabic (as well as some older Naskh fonts) fine, but chokes on Noto Nastaliq, and refused to even display any other Nastaliq font I have. I suspect that the cursive attachment feature is simply not supported, but positional variants are. 

All this makes me think that some of the problems have to do with how the apps interpret the font features, especially cursive attachment, and maybe the issue with “yeh” has to do with some hiddent subsitutions of yeh with dots and “Farsi” yeh without dots (why else just “yeh”?); but I don’t know any details about that.

I am running OS Yosemite on Mac. I’ll see if an OS update helps (I am not optimistic though, if the issue is app-dependent and not platform-dependent).

Noto Nastaliq Urdu is such a beautiful font, I really hope there will eventually be a version that works well in all respects.

Thanks.

**Comment by RolfNoyer** [comment] 2016-07-01 21:13
So I tried Noto Nastaliq Urdu on a friend’s machine running the latest Mac OS (El Capitán) instead of on mine with Yosemite.

In Mac’s Text Edit (at least — the only app I tried on his machine) the dot placement problem **disappeared completely** and as far as I could tell all the other diacritic mark placement problems I had noticed before also went away. 

So whatever this was, it must have been something wrong with Yosemite in the version I had, which had other bugs with complex text layout as well, which maybe they managed to get rid of in the next OS release (I noticed some other unrelated bugs had also vanished in some other fonts I use). 

Maybe you should include in a READ ME file with Noto Nastaliq that may not have optimal on-screen appearance in Yosemite, and an update in OS is recommended for Mac users still on the older system. The original problem was not limited to Text Edit, as I mentioned, but must have had something to do with the OS. To the extent that Mellel was not showing the problem, it must have been because it has some extra interpretive capacity that allowed it to bypass what the OS was doing in the other apps.

Also I noticed that when running El Capitán the “Draft” version of Noto Nastaliq was definitely inferior to the more recent release, which actually looks really good now.

**Comment by behdad** [comment] 2016-07-21 02:23
Closing as this seems to be working as intended with latest Mac OS X.

**Closed by behdad** 2016-07-21 02:23 UTC
Labels: Script-Urdu
