### ISSUE TITLE
Unicode line drawing in PuTTY with Noto Mono

### ISSUE THREAD

**Issue by xnoreq** [googlei18n/noto-fonts#757] opened 2016-10-08 12:49 UTC
PuTTY with "Use Unicode line drawing code points" and DejaVu Sans Mono, 10pt:
![2016-10-08](https://cloud.githubusercontent.com/assets/4028859/19213213/59fd5e24-8d65-11e6-8520-03d8eea3637e.png)

With the font changed to Noto Mono:
![2016-10-08 1](https://cloud.githubusercontent.com/assets/4028859/19213214/5b471bee-8d65-11e6-94ec-91f3fbf3573a.png)

Here's the portion copied out of the terminal:
```
──────────────┬─────────────
              │1............
    0.3|221  1│
```

Can we get nice unicode line drawing with Noto Mono?

**Comment by xnoreq** [comment] 2016-10-09 09:58
Box Drawing Unicode block: http://www.unicode.org/charts/PDF/U2500.pdf

**Comment by jungshik** [comment] 2016-10-10 21:41
@dougfelt

**Comment by dougfelt** [comment] 2016-10-10 22:32
Ref #617

**Comment by jungshik** [comment] 2016-10-11 17:35
Is there anything in this bug that won't be resolved when we take care of #617?

**Comment by dougfelt** [comment] 2016-10-11 22:36
Closed as duplicate of #617.

**Closed by dougfelt** 2016-10-11 22:36 UTC
Labels: Script-Monospace, Script-Symbol
