### ISSUE TITLE
Latin and Cyrillic iotas design issues

### ISSUE THREAD

**Issue by moyogo** [googlei18n/noto-fonts#496] opened 2015-09-04 07:57 UTC
The Latin iota should be distinct from the Latin i (both uppercase and lowercase). The same goes for the Cyrillic iota (see http://www.unicode.org/L2/L2007/07003r-n3194r-cyrillic.pdf). Especially since they can all be used with diacritics, the i losing its tittle, both lowercase must be different.

See the following with Arimo, Cousine, Tinos, Noto Sans, Noto Serif (in that order) in roman and then in italic: IiƖɩᵼᶥꙆꙇ (U+0049 U+0069 U+0196 U+0269 U+1D7C U+1DA5 U+A646 U+A647)
![screen shot 2015-09-04 at 08 42 07](https://cloud.githubusercontent.com/assets/1923747/9678815/e2a59df6-52e0-11e5-93b4-fbddbdff75bf.png)

In Arimo, the Latin Ɩᵼᶥ (U+0196 U+1D7C U+1DA5) must have a hook-tail terminal; the terminal of Cyrillic iota ꙇ U+A647 is too subtle, it should be like the Latin iota with a hook-tail terminal, and Ꙇ U+A646 should have a hook-tail terminal as well.

In Cousine, Ɩᵼᶥ (U+0196 U+1D7C U+1DA5) must have a hook-tail terminal, the Cyrillic iotas are missing.

In Tinos, Latin Ɩ U+0196 should have both left and right top serifs and a hook-tail in italic, Cyrillic Ꙇ U+A646 should have a hook-tail as well.

In Noto Sans and Noto Serif, the Latin iotas are good, the Cyrillic iotas are missing.

**Comment by marekjez86** [comment] 2016-04-27 01:02
@KatMomoi : please check if the missing Cyrillic iota ꙇ U+A647 is present now in Cousine, Noto Serif and Noto Sans

**Comment by KatMomoi** [comment] 2016-04-29 05:50
I've looked at the latest Noto Sans (all LGC varieties), Noto Serif (all LGC varieties) and Cousine fonts. I can confirm that all these LGC fonts **have** the Cyrillic Small Letter Iota (U+A647).

**Comment by marekjez86** [comment] 2016-05-17 15:01
This bug is from now on used ONLY for Noto issues. For Arimo, Cousine or Tinos issues please see https://github.com/googlei18n/noto-fonts/issues/684 .

Since I created bug https://github.com/googlei18n/noto-fonts/issues/684 to track Arimo, Cousine or Tinos issues, I'm removing the ArimoTinosCousine label here.

**Comment by KatMomoi** [comment] 2016-09-01 22:13
I am closing this bug belatedly as there are no Noto issues left and whatever Arimo, Cousine and Tino issues there are tracked in bug #684.

**Closed by KatMomoi** 2016-09-01 22:13 UTC
Labels: Android, Priority-Medium, Script-LatinGreekCyrillic, Type-Defect
