### ISSUE TITLE
Combine Chakma and Latin glyphs

### ISSUE THREAD

**Issue by Bivuti** [googlei18n/noto-fonts#915] opened 2017-05-12 19:28 UTC
I am Bivuti Chakma from Bangladesh. I got Noto Sans Chakma font for review. I tested the font there is no latin glyph. When I edit my ccp-keyboard.xml file that now support latin glyph.Is it possible to include latin glyph with Noto Sans Chakma font? 
![xml noto ccp](https://cloud.githubusercontent.com/assets/13092086/26013686/60ef6a7c-377b-11e7-8afa-86d5864da278.JPG)
![xml noto ccp-2](https://cloud.githubusercontent.com/assets/13092086/26013701/6bb4c038-377b-11e7-87b4-30640118ae20.JPG)

Or, how can I merge them together? Or if you could provide a merged font with both 
English and Chakma support, that would be great.

Bivuti Chakma
From Bangladesh
Email: bsereye@hotmail.com

**Comment by TidharC** [comment] 2017-06-12 18:30
@Bivuti, it is my understanding that the exclusion of Latin script from non-Latin Noto fonts is by design.

Reassigning to @marekjez86, @dougfelt for further comment and recommendations.

**Comment by brawer** [comment] 2017-06-29 17:28
Yes, this is intentional; Android (the main “customer” for the Noto font) prefers to have each script packaged in a separate file. But there’s tools that can merge multiple font files into a single package; have a look at the `pyftmerge` tool from [fonttools](https://github.com/fonttools/fonttools).

**Closed by brawer** 2017-06-29 17:28 UTC

**Comment by Bivuti** [comment] 2017-07-03 10:23
@brawer Thanks a lot. If so, then there are lots of benefit for us. I look forward the Noto Sans Chakma next ver will fix this issue.
