### ISSUE TITLE
Khmer font naming appears incorrect

### ISSUE THREAD

**Issue by GoogleCodeExporter** [googlei18n/noto-fonts#227] opened 2015-06-08 18:33 UTC
```
If you install Noto Serif Khmer the font is called Battambang in the Mac OS 
font tool.  The font installer says "1 minor problem was found. Proceed with 
caution."  You can see that the font will be called Battambang in the title bar 
of the installation window.


If you try to install Noto Sans Khmer on the Mac OS (Yosemite) you get the same 
warning, but the title bar of the installation dialog box says Noto Sans Khmer. 
 However, no such named font appears in the list of fonts after installation, 
and I have no clue whether it has been installed under a different name either 
- i just can't see what, if anything, was installed. 
```

Original issue reported on code.google.com by `richardi...@gmail.com` on 2 Jan 2015 at 9:23

**Comment by fontguy** [comment] 2015-07-31 23:22
I'm unable to reproduce this. I see no warning on installation or other name during installation. Can you try removing the font in Font Book and trying to install again? If you do still see the error could you grab a screen shot (Command+Shift+4)?

I will close it until I get more info.

**Closed by fontguy** 2015-07-31 23:22 UTC
Labels: Script-Khmer, Status-Unreproducible, Type-Defect
