### ISSUE TITLE
Kannada complex rendering broken on Java based applications

### ISSUE THREAD

**Issue by yogiks** [googlei18n/noto-fonts#737] opened 2016-08-29 15:09 UTC
Saw this on two Java-based applications: [JOSM](https://josm.openstreetmap.de/) and [Freeplane](http://www.freeplane.org/wiki/index.php/Main_Page). Below are the screenshots and corrections:

Incorrect rendering on JOSM-

![josm](https://cloud.githubusercontent.com/assets/6291913/18055172/6ca5d14c-6e24-11e6-93ee-db793d789734.png)

Expected correct rendering: ಕೆಂಭಾವಿ ಆರೋಗ್ಯ ಉಪಕೇಂದ್ರ. As it is shown above, ಆರೋಗ್ಯ and ಉಪಕೇಂದ್ರ are broken.

Again the same is seen on another Java based application - Freeplane-

![freeplane](https://cloud.githubusercontent.com/assets/6291913/18055171/6ca4d30a-6e24-11e6-9f0f-ad80b4ef2eea.png)

But I can see this renders correctly with [Gubbi](https://github.com/aravindavk/Gubbi) and other Kannada fonts -

![Correct rendering in Gubbi](https://cloud.githubusercontent.com/assets/6291913/18055170/6c4e3c98-6e24-11e6-9ddc-8f694fe1b549.png)

Above screenshots are from Ubuntu GNU/Linux and this might also be the case on Java-based applications on other platforms if Noto Sans Kannada is the default font used on these applications.

**Comment by marekjez86** [comment] 2016-08-29 23:19
![kannada](https://cloud.githubusercontent.com/assets/13322623/18070532/49a295f2-6e03-11e6-926a-6970031a3417.jpg)

top line: NotoSerifKannada-Regular.otf (using https://github.com/googlei18n/noto-fonts/blob/master/unhinted/NotoSerifKannada-Regular.ttf )
bottom: NotoSansKannada-Regular.otf (using https://github.com/googlei18n/noto-fonts/blob/master/unhinted/NotoSansKannada-Regular.ttf )

Does any of them look right?

**Comment by yogiks** [comment] 2016-08-30 08:59
Nope. 

### On top line
![kembavi-wrong](https://cloud.githubusercontent.com/assets/6291913/18076227/b5ae0718-6e99-11e6-8791-88e528c72722.png) looks wrong. Correct rendering would be 
![giht-kembavi](https://cloud.githubusercontent.com/assets/6291913/18076237/d5fa3cbc-6e99-11e6-8876-5e8f08812307.png). But ಆರೋಗ್ಯ ಉಪಕೇಂದ್ರ looks right.
![right-au](https://cloud.githubusercontent.com/assets/6291913/18076295/5b537626-6e9a-11e6-8f3e-64c03c270630.png)


### On bottom line
All three words are wrong at the joining of two characters. Right rendering would look like this - 
![correct](https://cloud.githubusercontent.com/assets/6291913/18082711/abf5228c-6ebd-11e6-883a-6794575a6700.png) with NotoSansKannada(screenshot from LibreOffice)


Thank you for getting back.

**Comment by KatMomoi** [comment] 2016-09-01 22:36
Let us send this over to Sue/MTI first for evaluation. If the issue is elsewhere, please assign it back to us.

**Comment by JelleBosmaMT** [comment] 2016-09-06 15:16
**On behalf for waksmonskiMT**

There are two options for rendering: first the old "windows XP" style rendering with the knda script tag. Which looks like this in Windows XP:
![winxp](https://cloud.githubusercontent.com/assets/12729011/18278020/d2e60918-7450-11e6-8533-00aa14087ad9.png)
No Problem.

Secondly there is improved rendering through the tag knd2. It looks like this in Windows 7:
![win7](https://cloud.githubusercontent.com/assets/12729011/18278067/021b2132-7451-11e6-824c-e86d19791e9b.PNG)
I do not see anything bad.

If course in the second comment by yogis, Noto Sans Kannada is used to show the correct rendering in LibreOffice. (The spacing looks quite bad, however)

For the original knda rendering, the virama between base consonant and intended subscript consonant is moved after intended subscript, which is then created as Consonant + virama = subscript ligature. For knd2 that re-ordering does not happen: virama + consonant = subscript ligature. In the samples from JOSM and FreePlane (I have no idea what that is), this knda re-ordering has taken place. Maybe it is knd2 rendering with knda re-ordering? Who knows? In any case: if the fonts are OK in old and new Windows rendering, the fonts are OK.

**Comment by jungshik** [comment] 2016-09-07 18:27
I don't think this is a font issue. It's a Java issue.

**Comment by yogiks** [comment] 2016-09-07 19:26
@JelleBosmaMT 
The fonts are fine in text editors on Ubuntu too but issue is it doesn't render correctly with Java applications(i.e, [JOSM](https://josm.openstreetmap.de/) and [Freeplane](http://www.freeplane.org/wiki/index.php/Main_Page) in above examples) although other Kannada unicode fonts work as expected(See [3rd pic](https://cloud.githubusercontent.com/assets/6291913/18055170/6c4e3c98-6e24-11e6-9ddc-8f694fe1b549.png) in my [1st post above](https://github.com/googlei18n/noto-fonts/issues/737#issue-173797397) where [Gubbi](https://github.com/aravindavk/Gubbi) is used in same application). I guess you can reproduce this issue on Windows also on any Java-based applications like Freeplane(it's FOSS and available for Windows) with Noto Sans Kannada font for Kannada text.

@jungshik 
You're right, I only see this on Java applications. But I think there's something to do with Noto Sans Kannada font since the same doesn't happen with rest of the Kannada unicode fonts like Gubbi, Lohit Kannada, Navilu, etc.,.

**Comment by dougfelt** [comment] 2016-09-07 19:35
I assume this is with Java 8?  I think it still uses ICU layout.  My guess is ICU doesn't process the Kannada quite right.  My understanding is Java 9 will use Harfbuzz and perhaps that will fix this.

**Comment by JelleBosmaMT** [comment] 2016-09-08 06:56
The Gubbi font has both knda and knd2 rendering. But knd2 is seriously
buggy. The blwf feature is missing and in Windows 7-10 the subscripts do
not form. So in Java it must still be the knda rendering that is used.
We tested Noto with two different knda renderers.

I cannot do anything but speculate at this stage: Noto Sans Kannada is at
the moment not active as project. The question is for how long it makes
sense to support the old Indic rendering anyway.

**Comment by yogiks** [comment] 2016-09-14 06:11
@dougfelt yes, this is with Java 8.

@JelleBosmaMT right, Gubbi hasn't been active since past few years nor any other open license Kannada unicode fonts afaik. Would be good if Java 9 will fix this.

**Comment by jungshik** [comment] 2016-09-20 07:18
I don't think there's anything to do here because it's not a font issue.

**Closed by jungshik** 2016-09-20 07:18 UTC
Labels: Script-Kannada, Type-Defect
