### ISSUE TITLE
IPA: ligature ties (035C 0361) is not positioned properly with superscript letters

### ISSUE THREAD

**Issue by moyogo** [googlei18n/noto-fonts#536] opened 2015-10-25 16:28 UTC
See the following example with 0361 from Erik John Anonby, “Mambay”, _Journal of the International Phonetic Association_, Cambridge University Press, 36-2,‎ 2006 (DOI 10.1017/S0025100306002635)
![screen shot 2015-10-25 at 16 16 18](https://cloud.githubusercontent.com/assets/1923747/10716523/f0c97120-7b33-11e5-8adf-e0a5d80a8512.png)

This is not how 0361 is positioned in Arimo, Cousine, Tinos, Noto Sans, Noto Serif: k͡pᵑ͡ᵐ
![screen shot 2015-10-25 at 16 20 07](https://cloud.githubusercontent.com/assets/1923747/10716540/6be20d4a-7b34-11e5-9535-7b9d24f73876.png)

The ligature tie above 0361 should be right above the pair of superscript letters. If necessary it could be smaller as well.
One would expect the ligature tie below 035C to behave the same way as well: it should be right below the pair of superscript letters, not below the baseline.

**Comment by TrueTyper** [comment] 2015-11-23 19:51
Fixed in source for NotoSerif-RomanMM.glyphs.

**Comment by jungshik** [comment] 2016-04-26 20:33
@TrueTyper : Is this fixed in Arimo, Cousine, Tinos as well?

**Comment by marekjez86** [comment] 2016-05-12 00:56
the most recent Arimo (lower line)
![arial-arimo](https://cloud.githubusercontent.com/assets/13322623/15201028/6fcdeb90-17a1-11e6-915d-49bb5b8b18b1.jpg)
the most recent Cousine  (lower line)
![courier-cousine](https://cloud.githubusercontent.com/assets/13322623/15201035/8a771840-17a1-11e6-86d3-ed43a4f7cb78.jpg)
the most recent Tinos  (lower line)
![times_new_roman-tinos](https://cloud.githubusercontent.com/assets/13322623/15201041/9910dc92-17a1-11e6-9fe5-f80b0de0f012.jpg)

**Comment by marekjez86** [comment] 2016-05-13 00:53
I the above images the top line (pinkish) is from the precursor of a corresponding Google font. We seem to be compatible with the "originals" as far as "presence of issues" is concerned.

**Comment by moyogo** [comment] 2016-05-13 07:51
I’m sorry if the examples provided were misleading. I should have clarified the position of 0361 on the lowercase letters was correct initially (except for Cousine). Both positions (above x-height or above ascender-height with k͡p) are correct when the base glyphs allow it, but of course only above ascender-height works in cases like d͡z or above x-height works better in cases like n͡z.

Here’s k͡p in https://www.internationalphoneticassociation.org/sites/default/files/IPA_Kiel_2015.pdf
![screen shot 2016-05-13 at 08 44 06](https://cloud.githubusercontent.com/assets/1923747/15241300/f48bdc84-18e6-11e6-8f58-a37b3cda8737.png)

**Comment by jungshik** [comment] 2016-10-12 22:47
@marekjez86  Did you remove Script-Latin-Greek-Cyrillic because you confirmed that everything works fine in the latest delivery of Noto Sans and Noto Serif?  

Given @moyogo's new comment about a need for context-dependent positioning, this need to be re-examined anyway. 

@KatMomoi, can you get examples given by @moyogo tested by all LGC fonts (Noto Sans, Noto Serif, Arimo, Tinos and Cousine)?  Thank you

**Comment by brawer** [comment] 2016-10-13 08:51
@moyogo (and others), I wonder if it might be possible to come up with a document that explains to type designers what exactly they need to do for supporting IPA. Obviously this would cover the needed ligatures and diacritics, but also topics like which Greek glyphs should get substituted by “latinized” letterforms in OpenType language system IPPH. Ideally, we could also publish a plaintext file (in Unicode encoding) with test cases that font designers should check. What do you think? Would you want to start something?

Obviously it’d be a bit of work to write this, but as a result we’d move *all* IPA fonts towards a better working state, not just Noto.

**Comment by brawer** [comment] 2016-10-13 09:40
See https://github.com/googlei18n/noto-source/pull/27 for a proposal how these test cases could look like. Just a stub for now, but it would just take a few hours of browsing Wikipedia to make it more comprehensive. From a typographic perspective, it would probably be good to have the letters in context; but it’s all available on Wikipedia. (And we don’t really care if the samples are linguistically correct, as long as they reflect what people want to render).

**Comment by TidharC** [comment] 2016-11-03 22:45
Retested the same char sequence, which currently looks like this:
![iparendering](https://cloud.githubusercontent.com/assets/16353803/19988257/731f0656-a1dc-11e6-82b4-c2c33d362331.png)

**Comment by moyogo** [comment] 2016-11-22 06:29
@TidharC LGTM

**Closed** 2016-11-22 11:29 UTC
Labels: ArimoTinosCousine, Priority-Medium, Script-LatinGreekCyrillic

**Comment by marekjez86** [comment] 2017-01-03 23:44
MTI note: "Kamal thinks adding Mark to base placements of ties for all superior glyphs is beyond the scope of the job. Best we can do is general positioning ties over most normal letters. Superior positioning of ties would require additional work. Adjust anchor position in 03BC and 0361 to make tie position generally better over base letters."
