### ISSUE TITLE
Greek phi symbol 03D5 ϕ should have a stroked glyph in Noto Serif

### ISSUE THREAD

**Issue by moyogo** [googlei18n/noto-fonts#512] opened 2015-09-09 07:44 UTC
ϕ 03D5 is intended to be used as a technical symbol with a specific shape, it should have a stroke going from ascender height to descender height.
Its description in the Unicode chart is:
• used as a technical symbol, with a stroked glyph
• maps to 'phi1' symbol entities

See Noto Sans and Noto Serif with φϕ φ 03C6 03D5
![screen shot 2015-09-09 at 08 38 33](https://cloud.githubusercontent.com/assets/1923747/9756034/cce7c29a-56ce-11e5-8dd7-7cd8fdda4652.png)

In Noto Serif:
* ϕ 03D5 should have a full stroke.

**Comment by roozbehp** [comment] 2015-09-30 00:02
Confirming the bug.

**Comment by SteveMatteson** [comment] 2015-10-15 21:18
This Greek letter may be written both ways. This is not a bug but a design characteristic of the typeface. Unicode says it ~03C6 so the design should be consistent depending on which way the designer intends.

**Comment by moyogo** [comment] 2015-10-16 05:05
The issue is not about φ 03C6, but ϕ 03D5.

The Unicode chart provides the following description for 03D5:
• used as a technical symbol, with a stroked glyph
• maps to 'phi1' symbol entities
≈ 03C6 greek small letter phi

In math fonts both 03C6 and 03D5 would have to have specific forms.
There is no problem if the letter 03C6 is not designed for math usage here, but 03D5 is not supposed to be the opposite of 03C6, it is supposed to be the phi symbol with a stroke.

**Comment by roozbehp** [comment] 2015-10-19 22:39
Confirming @moyogo's comment that U+03D5 should always have a stroke.

**Comment by roozbehp** [comment] 2015-10-19 22:44
I just filed https://github.com/googlei18n/noto-fonts/issues/533 about the inconsistency between Sans and Serif. Using this bug for the problem with with phi1.

**Comment by SteveMatteson** [comment] 2015-10-20 04:57
It's intentional - for UI the long bar is a bit distracting. For text it's more formal. But we can make the two consistent if Google wishes.

**Comment by roozbehp** [comment] 2015-10-20 05:34
@SteveMatteson, I'm confused. Are you saying U+03D5 not having a long bar is intentional? How can a math symbol appearing as it should always appear be distracting? Or is [your comment above](https://github.com/googlei18n/noto-fonts/issues/512#issuecomment-149433396) in reference to https://github.com/googlei18n/noto-fonts/issues/533?

**Comment by TrueTyper** [comment] 2015-11-19 16:35
This has been fixed in source for NotoSerif-RomanMM.glyphs.

**Comment by xiangyexiao** [comment] 2016-02-28 20:16
The wanted timeline by Android is April/May.

**Comment by xiangyexiao** [comment] 2016-03-01 20:00
@waksmonskiMT, we want it to be fixed in Phase II fonts by end of March. Let me know if it is infeasible.

**Comment by xiangyexiao** [comment] 2016-03-03 23:23
@waksmonskiMT, you don't need to do anything for Phase 2.

@marekjez86 please pass TTF file converted from Phase 3 glyph to Jungshik, and Jungshik will add U+03D5 to Noto Serif for Phase II.

**Comment by marekjez86** [comment] 2016-03-04 11:15
passed the font file to @jungshik

**Comment by jungshik** [comment] 2016-03-15 23:20
We can close because they're fixed in both Phase 2 and Phase 3.

**Closed by jungshik** 2016-03-15 23:20 UTC
Labels: Android, GNTF, Priority-High, Script-LatinGreekCyrillic, Type-Defect

**Comment by thlinard** [comment] 2020-02-25 14:56
Adobe provides the corrected version:
https://fonts.adobe.com/fonts/noto-serif

**Comment by SteveMatteson** [comment] 2020-02-25 15:55
The phi can take either shape - with our without a complete stroke.
steve
________________________________
